Pyramid/Controllers/EventBannerController.cs
using DBFirstDAL.Repositories;
using Pyramid.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pyramid.Controllers
{
    [Authorize]
    public class EventBannerController : Controller
    {
        EventBannerRepository _eventBannerRepository;

        public EventBannerController() {
            _eventBannerRepository = new EventBannerRepository();
        }
        // GET: EventBanner
        public ActionResult Index()
        {
            var model = _eventBannerRepository.GetAll();
            return View(model);
        }
        public ActionResult AddOrUpdate(int id = 0)
        {
            var model = _eventBannerRepository.Get(id);
            if (model==null)
            {
                model = new EventBanner();
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult AddOrUpdate( EventBanner model)
        {
            _eventBannerRepository.AddOrUpdate(model);
            return RedirectToAction("Index");

        }
        public ActionResult Delete(int id)
        {
            _eventBannerRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Pyramid/Views/EventBanner/AddOrUpdate.cshtml
@model Pyramid.Entity.EventBanner
@{
    ViewBag.Title = "Редактирование Банера";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="section-header">
    <h2>@ViewBag.Title</h2>
</div>
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-lg-8 col-md-8">

            <div class="box-typical box-typical-padding">
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.HiddenFor(m => Model.Thumbnail.Id, new { id = "ThumbnailId" })
                            <div class="admin-product__thumbnail">
                                <img src="@((Model.Thumbnail!=null)? Model.Thumbnail.ServerPathImg:"#")" alt="" />
                            </div>
                           
                            <button class="btn btn-primary js-btn-thumbnail-edit" type="button">Изменить картинку</button>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Сохранить" class="btn btn-default" />
                        </div>
                    </div>
                </div>

            </div>


        </div>

    </div>
}

<div class="modal fade" id="edit-thumbnail-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Выбор картинки</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                @*<button type="button" class="btn btn-primary js-btn-thumbnail-save">Сохранить изменения</button>*@
            </div>
        </div>
    </div>
</div>

Pyramid/Views/EventBanner/Index.cshtml
@model IEnumerable<Pyramid.Entity.EventBanner>
@{
    ViewBag.Title = "Баннеры на сайте";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="section-header">
    <h2>@ViewBag.Title</h2>
    <div class="subtitle">информация</div>
</div>


<p class="pmargin">
    @Html.ActionLink("Добавить новый баннер", "AddOrUpdate", null, new { @class = "btn btn-primary" })
</p>

<table class="table table-bordered table-hover">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>


                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <div class="btn-group btn-group-sm" style="float: none;">
                        <a href="@Url.Action("AddOrUpdate", "EventBanner", new { id = item.Id })" class="tabledit-edit-button btn btn-sm btn-default" style="float: none;">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>
                        <a href="@Url.Action("Delete", "EventBanner", new { id = item.Id })" class="tabledit-delete-button btn btn-sm btn-default" style="float: none;">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </div>

                </td>
            </tr>
        }

</table>