Pyramid/Controllers/CartController.cs
using DBFirstDAL.Repositories;
using Pyramid.Entity;
using Pyramid.Models.Cart;
using Pyramid.Tools;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Pyramid.Tools.Mailer;

namespace Pyramid.Controllers
{
    public class CartController : BaseController
    {
        private OrderRepository _orederRepository;
        private ProductRepository _productRepository;
        private FeedBackEmailRepository _feedBackEmailRepository;
        public CartController()
        {
            _productRepository = new ProductRepository();
            _orederRepository = new OrderRepository();
            _feedBackEmailRepository = new FeedBackEmailRepository();
        }

        public ActionResult AddToCart(int productId, int quantity)
        {

            var line = GetCart().Lines.FirstOrDefault(i => i.Product.Id == productId);
            if (line == null)
            {
                var product = _productRepository.Get(productId);
                if (product != null)
                {

                    GetCart().AddItem(new ProductCartModel()
                    {
                        Id = product.Id,
                        Price = product.Price,
                        Title = product.Title,
                        Picture = product.ThumbnailImg
                    }
                    , quantity);
                }
            }
            else
            {
                line.Quantity += quantity;
            }

            return Json(new { Action = "Add", Status = "ok", AllAmount = GetCart().Lines.Count() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SetQuantityToCart(int productId, int quantity)
        {
            var line = GetCart().Lines.Where(i => i.Product.Id == productId).FirstOrDefault();
            if (line != null)
            {
                GetCart().SetQuantity(productId, quantity);
            }
            return Json(new { Action = "Add", Status = "ok", AllAmount = GetCart().Lines.Count() }, JsonRequestBehavior.AllowGet);

        }

        //public ActionResult RemoveFromCart(int productId)
        //{
        //    GetCart().RemoveLine(productId);
        //    return Json(new { Status = "ok" });
        //}

        public ActionResult PartialShortCart()
        {
            return PartialView("_PartialShortCart", GetCart());
        }
        public ActionResult ShowCart()
        {
            ViewBag.MetaTitle = "Корзина";
            return View(GetCart());
        }

        public ActionResult Checkout()
        {
            ViewBag.MetaTitle = "Подтверждение заказа";

            return View(new CheckoutModel());
        }
        [HttpPost]
        public ActionResult Checkout(CheckoutModel model)
        {
            ValidateModel(model);
            var cart = new Cart( GetCart());
            
            var emailModel = new CartOrderFromEmailSendModel()
            {
                Cart=cart,
                UserData=model
            };
            var message = RenderViewToString(this.ControllerContext, "/Views/Cart/_PartialNewOrderFromEmailSend.cshtml", emailModel, true);

           
            var entity = new Order()
            {
                Adress = model.Adress,
                Email = model.Email,
                Phone = model.Phone,
                TypeProgressOrder = (int)Entity.Enumerable.TypeProgressOrder.SimplePrice,
                UserName = model.Name,
                Products = cart.Lines.Select(i => new OrderProduct()
                {
                    Product = new Product() { Id = i.Product.Id },
                    Quantity = i.Quantity
                }).ToList(),
                DateOrder=DateTime.Now
            };
            
            MailerMessage mailerMessage = new MailerMessage();
            mailerMessage.Body = message;
            mailerMessage.Subject = "Заказ с сайта Пирамида строй";
            mailerMessage.To = _feedBackEmailRepository.GetAll().Select(i => i.Email).ToList();
            mailerMessage.SenderName = "Pyramid";

            if (mailerMessage.To.Count > 0)
            {
                Mailer.Send(mailerMessage);
            }
            
            GetCart().Clear();
            bool flagErr = false;
            try
            {
                _orederRepository.Add(entity);
            }
            catch (Exception)
            {
                flagErr = true;
            }
            ViewBag.IsAddedOrder = !flagErr;

            ViewBag.MetaTitle = "Подтверждение заказа";
            return View("ResultCheckout", cart);
        }
        public ActionResult RemoveItem(int id)
        {
            GetCart().RemoveLine(id);
            return Json(new { Action = "Remove", Status = "ok", AllAmount = GetCart().Lines.Count() }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult PartialGetCard()
        {
            return PartialView("PartialGetCard", GetCart());
        }

        public ActionResult CheckoutOneClick(int id)
        {
            var product = _productRepository.Get(id);
            ViewBag.Product = product;
            ViewBag.MetaTitle = "Подтверждение заказа";
            return View(new CheckoutModel());
        }
        [HttpPost]
        public ActionResult CheckoutOneClick(CheckoutModel model, int productId)
        {
            ValidateModel(model);
            var product=_productRepository.Get(productId);

            List<CartLine> lineCollection = new List<CartLine>();
            lineCollection.Add(new CartLine()
            {
                Quantity = 1,
                Product = new ProductCartModel()
                {
                    Id = product.Id,
                    Price = product.Price,
                    Title = product.Title
                }
            });
            var emailModel = new CartOrderFromEmailSendModel()
            {
                Cart = new Cart(lineCollection),
                UserData = model
            };
            var message = RenderViewToString(this.ControllerContext, "/Views/Cart/_PartialNewOrderFromEmailSend.cshtml", emailModel, true);

            var entity = new Order()
            {
                Adress = model.Adress,
                Email = model.Email,
                Phone = model.Phone,
                TypeProgressOrder = (int)Entity.Enumerable.TypeProgressOrder.SimplePrice,
                UserName = model.Name,
                Products = new List<OrderProduct>(new OrderProduct[] { new OrderProduct() {
                    Product=new Product() {Id=productId },
                    Quantity=1
                } }),
            };
            MailerMessage mailerMessage = new MailerMessage();
            mailerMessage.Body = message;
            mailerMessage.Subject = "Заказ с сайта Пирамида строй";
            mailerMessage.To = _feedBackEmailRepository.GetAll().Select(i => i.Email).ToList();
            mailerMessage.SenderName = "Pyramid";

            if (mailerMessage.To.Count > 0)
            {
                Mailer.Send(mailerMessage);
            }

            bool flagErr = false;
            try
            {
                _orederRepository.Add(entity);
            }
            catch (Exception ex)
            {
                flagErr = true;
            }
            ViewBag.IsAddedOrder = !flagErr;
            return View("ResultCheckoutOneClick");
        }
    }
}

Pyramid/Controllers/EventController.cs
using Common.Models;
using Common.SearchClasses;
using DBFirstDAL.Repositories;
using Entity;
using PagedList;
using Pyramid.Entity;
using Pyramid.Global;
using Pyramid.Models.CommonViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pyramid.Controllers
{   [Authorize]
    public class EventController : BaseController
    {
        private CategoryRepository _categoryRepository;
        private EventRepository _eventRepository;
        EventBannerRepository _eventBannerRepository;
        RouteItemRepository _routeItemRepository;

        public EventController()
        {
            _eventRepository = new EventRepository();
            _categoryRepository = new CategoryRepository();
            _eventBannerRepository = new EventBannerRepository();
            _routeItemRepository = new RouteItemRepository();

        }
        // GET: Event
        [AllowAnonymous]
        public ActionResult Index()
        {
            List<BreadCrumbViewModel> breadcrumbs = new List<BreadCrumbViewModel>();
            breadcrumbs.Add(new BreadCrumbViewModel()
            {
                Title = "Акции"
            });
            ViewBag.BredCrumbs = breadcrumbs;
            var model  = _eventRepository.GetAll().ToList();
            ViewBag.Banners = _eventBannerRepository.GetAll();
            ViewBag.MetaTitle = "Акции";
            return View(model);
        }
        [AllowAnonymous]
        public ActionResult Get(int id)
        {
            var model = _eventRepository.Get(id);
            if (model != null)
            {
                List<BreadCrumbViewModel> breadcrumbs = new List<BreadCrumbViewModel>();
                breadcrumbs.Add(new BreadCrumbViewModel()
                {
                    Link = "/Event/Index",
                    Title = "Акции",
                    FriendlyUrl = string.Format("/{0}", new GlobalOptionRepository().Get(Common.Constant.KeyEvent).OptionContent)
                });
                breadcrumbs.Add(new BreadCrumbViewModel()
                {
                    Title = model.Title
                });
                ViewBag.BredCrumbs = breadcrumbs;
            }
            var friendlyUrl = _routeItemRepository.GetFriendlyUrl(model.Id, Common.TypeEntityFromRouteEnum.Event);
            ViewBag.CurrentFriendlyUrl = friendlyUrl;
            ViewBag.Banners = _eventBannerRepository.GetAll();
            ViewBag.MetaTitle = model.Title;

            return View(model);
        }
        public ActionResult ManageIndex(int? page)
        {
            var pageNumber = page ?? 1;

            var objectsPerPage = 20;
            var startIndex = (pageNumber - 1) * objectsPerPage;

            SearchParamsBase SearchParams = new SearchParamsBase(startIndex, objectsPerPage);

            var searchResult = _eventRepository.Get(SearchParams);

            var viewModel = SearchResultViewModel<Pyramid.Entity.Event>.CreateFromSearchResult(searchResult, i => i, 10);

            return View(viewModel);
        }
        public ActionResult AddOrUpdate(int id=0)
        {
           var model= _eventRepository.Get(id);
            if (model == null)
            {
                model = new Event() {
                    DateEventEnd=DateTime.Now,
                    DateEventStart= DateTime.Now,
                };
            }            
            var friendlyUrl = _routeItemRepository.GetFriendlyUrl(model.Id, Common.TypeEntityFromRouteEnum.Event);
            ViewBag.CurrentFriendlyUrl = friendlyUrl;

            return View(model);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddOrUpdate(Event model)
        {
            _eventRepository.AddOrUpdate(model);
            var routeItem = new RouteItem(0, null, (string)ControllerContext.RequestContext.RouteData.Values["controller"],
              "Get",
              model.Id)
            { Type = Common.TypeEntityFromRouteEnum.Event };

            _routeItemRepository.AddOrUpdate(routeItem);
            ViewData["OperationResult"] = "Операция прошла успешно";
            return RedirectToAction("ManageIndex");
        }

        public ActionResult Delete(int id)
        {
            var efEvent = _eventRepository.FindBy(i => i.Id == id).SingleOrDefault();
            _eventRepository.Delete(id);
            return RedirectToAction("ManageIndex");
        }

        public ActionResult TemplateCategoryFromEventProduct(int count,int eventId= 0)
        {
            var efEvent = _eventRepository.Get(eventId);
            var indx = 0;
            if (efEvent!=null&& efEvent.Products!=null)
            {
                indx = efEvent.Products.Count();
            }
            if (count>indx)
            {
                indx = count;
            }
            ViewBag.CategoriesSelectListItem = _categoryRepository.GetAll().Select(item => new SelectListItem
            {
                Text = item.Title,
                Value = item.Id.ToString()
            });
            return PartialView("TemplateCategoryFromEventProduct", indx);
        }
        public ActionResult TemplateEventProductFromCategoryId(int id, int index)
        {
            ViewBag.ProductsSelectListItem = _categoryRepository.GetProductsByCategoryId(id).Select(item => new SelectListItem
            {
                Text = item.Title,
                Value = item.Id.ToString()
            });
            return PartialView("TemplateEventProductFromCategoryId", index);
        }
        public ActionResult DeleteProduct(int id,int productid)
        {
            var result=_eventRepository.DeleteReletedProduct(id, productid);
            return Json(new {Status="ok",Result=result });
        }
    }
}

Pyramid/Views/Event/AddOrUpdate.cshtml
@model Pyramid.Entity.Event
@{
    ViewBag.Title = ((Model != null && Model.Id != 0) ? "Редактирование" : "Добавление") + " акции";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="section-header">
    <h2>@ViewBag.Title</h2>
</div>

@using (Html.BeginForm("AddOrUpdate", "Event", FormMethod.Post, new { id = "addOrUpdateEventForm" }))
{
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <div class="box-typical box-typical-padding">

                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => Model.Id,new {id="Event_Id" })
                <div class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ShortContent, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ShortContent, new { htmlAttributes = new { @class = "form-control adminTextareaCommon" } })
                            @Html.ValidationMessageFor(model => model.ShortContent, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control adminTextareaCommon" } })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DateEventStart, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateEventStart, new { htmlAttributes = new { @class = "form-control dateTimePicker", data_val_date="false"} })
                            @Html.ValidationMessageFor(model => model.DateEventStart, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DateEventEnd, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DateEventEnd, new { htmlAttributes = new { @class = "form-control dateTimePicker" } })
                            @Html.ValidationMessageFor(model => model.DateEventEnd, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.CheckBoxFor(model => model.isActive, htmlAttributes: new { })
                            @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">

                    </div>

                </div>
            </div>
            <div class="card">
                <div class="card-header card-header-lg">
                    <p>Баннер</p>
                </div>
                <div class="card-block">
                    <div class="event__img-wrap">
                        @Html.Hidden("Image.Id", Model!=null&& Model.Image != null ? Model.Image.Id : 0, new { id = "EventImage_Id" })


                        <img class="event__view-img" src="@(Model!=null&&Model.Image!=null?Model.Image.ServerPathImg:"")" alt="" />

                    </div>
                    <button type="button" class="btn btn-primary btn-update-event-image">Изменить</button>
                </div>

            </div>
            <div class="card">
                <div class="card-header card-header-lg">
                    <p>Товары</p>
                </div>
                <div class="card-block">
                    <div class="event__products">
                        @if (Model!=null&& Model.Products!=null)
                        {
                            var indx=0;
                            foreach (var item in Model.Products)
                            {
                                <div class="event__product">
                                    @Html.Hidden(string.Format("Products[{0}].Id", indx), item.Id)
                                    <label>@item.Title</label>
                                    <a class="btn-remove-event-product" data-actionurl="@Url.Action("DeleteProduct","Event",new { id=Model.Id,productId=item.Id})">Убрать</a>
                                </div>
                                indx++;
                            }
                        }
                        
                    </div>
                    <button type="button" class="btn btn-primary btn-add-event-product">Добавить</button>
                </div>

            </div>



        </div>
    </div>
    <div class="card">
        <div class="card-header card-header-lg">
            <p>Значение SEO параметров</p>
        </div>
        <div class="card-block">
            <div class="form-horizontal">
                @if (!string.IsNullOrEmpty(ViewBag.CurrentFriendlyUrl))
                {
                    <p style="color:gray">текущая ссылка: @ViewBag.CurrentFriendlyUrl</p>

                }
                <div class="form-group">
                    @Html.LabelFor(model => model.Seo.Alias, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Seo.Alias, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Seo.Alias, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Seo.MetaDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Seo.MetaDescription, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Seo.MetaDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Seo.MetaTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Seo.MetaTitle, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Seo.MetaTitle, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Seo.MetaKeywords, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Seo.MetaKeywords, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Seo.MetaKeywords, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="card">
        <div class="card-block">
            <div class="form-group">

                <input type="submit" value="Сохранить" class="btn btn-default">

            </div>
        </div>
    </div>

}


<div class="modal fade" id="edit-event-image-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Выбор картинки</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                @*<button type="button" class="btn btn-primary js-btn-thumbnail-save">Сохранить изменения</button>*@
            </div>
        </div>
    </div>
</div>

Pyramid/Views/Event/Get.cshtml
@model Pyramid.Entity.Event
@{
    ViewBag.Title = Model.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var modelFriendlyUrlBase = (FriendlyUrlBaseModel)ViewBag.FriendlyUrlBase;
}
<div class="page">
    <div class="page__title">@Model.Title</div>
    <div class="row no-gutter">
        <div class="col-f-lg-3 col-md-3 col-xs-3">
            <div style="text-align:center;">
                <button type="button" data-toggle="modal" data-target="#feedback-modal" class="btn btn-primary btn-green" style="margin-bottom:10px;">Обратная связь</button>
            </div>
            @Html.Partial("_PartialSliderOnPages")
        </div>

        <div class="col-f-lg-12 col-md-9 col-xs-9">
            <div class="row no-gutter">
                <div class="col-lg-12 col-xs-12">
                    <div class="page__event-banner">
                        <img class="page__event-banner-img" src="@(Model.Image!=null&&Model.Image.ServerPathImg!=null?Model.Image.ServerPathImg:"")" alt="" />
                    </div>
                </div>
                <div class="col-lg-12 col-md-12 col-xs-12">
                    <div class="page__content-wrap">
                        <div class="page__event-period">
                            Сроки проведения: @Model.DateEventStart.ToString("d") - @Model.DateEventEnd.ToString("d")
                        </div>
                        <div class="page__content">@MvcHtmlString.Create( Model.Content)</div>

                </div>
            </div>
            @foreach (var item in Model.Products)
                {
                <div class="col-lg-3 col-md-4 col-xs-4">
                    <div class="product__item">
                        <a href="@(!string.IsNullOrEmpty(item.FriendlyUrl)? item.FriendlyUrl : Url.Action("Index","Product",new { id=item.Id}))">
                            <img src="@(item.ThumbnailImg.ServerPathImg!=null?item.ThumbnailImg.ServerPathImg:Pyramid.Global.Config.PathNotFilledImage)" alt="" class="product__item-img">

                            <p class="product__item-title">@item.Title</p>
                            <div class="product__item-price @Pyramid.Tools.ProductTool.GetClassByTypePrice((int)item.TypePrice)">
                                <div class="triangle-up"></div>
                                <div class="triangle-down"></div>
                                <p class="product__item-price-inner"><span class="big-decimal">@item.Price</span> руб.</p>
                            </div>
                        </a>
                        <div class="product__item__hover_block_wrapper">
                            <div class="product__item__hover_block_wrapper__item product__in-stock @(item.TypeStatusProduct == Common.TypeStatusProduct.WillBeAdded?"product__in-stock_willbeadded":"")">
                                @if (item.TypeStatusProduct == Common.TypeStatusProduct.Normal)
                                {
                                    <p>в наличии</p>
                                }
                                @if (item.TypeStatusProduct == Common.TypeStatusProduct.WillBeAdded)
                                {
                                    <p>Доступен для заказа</p>
                                }
                            </div>
                            <a class="product__item__hover_block_wrapper__item" href="@Url.Action("CheckoutOneClick","Cart",new { id=item.Id})">
                                <div class="product__buy product__buy_one-click">
                                    <p>Купить в один клик</p>
                                </div>
                            </a>
                            <span class="product__item__hover_block_wrapper__item js-add-to-cart" data-ajaxid="@item.Id">
                                <span class="product__buy product__buy_add-to-cart">
                                    Добавить в корзину
                                </span>
                            </span>
                        </div>
                    </div>
                </div>

                }
            <div class="col-lg-12 col-md-12 col-xs-12">

                <a href="@(!string.IsNullOrEmpty(modelFriendlyUrlBase.EventBaseFriendlyUrl)? modelFriendlyUrlBase.EventBaseFriendlyUrl : Url.Action("Index","Event"))" class="page__link-event">Все акции</a>


            </div>
        </div>
    </div>

</div>
</div>

<div class="modal fade" id="feedback-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Обратная связь</h4>
            </div>
            @{var feedback = new Common.FeedBack(); }
            <div class="modal-body">
                <form action="#" class="feedback-form-modal">

                    <div class="form-group call-to-action__form-group">
                        @Html.TextBoxFor(m => feedback.Name, new { @class = "form-control call-to-action__form-control", placeholder = Html.DisplayNameFor(d => feedback.Name) })
                        @Html.ValidationMessageFor(m => feedback.Name)

                    </div>
                    <div class="form-group call-to-action__form-group">
                        @Html.TextBoxFor(m => feedback.Email, new { @class = "form-control call-to-action__form-control", placeholder = Html.DisplayNameFor(d => feedback.Email) })
                        @Html.ValidationMessageFor(m => feedback.Email)
                        @*<input type="text" class="form-control call-to-action__form-control" placeholder="E-mail">*@
                    </div>
                    <div class="form-group call-to-action__form-group">
                        @Html.TextBoxFor(m => feedback.Phone, new { @class = "form-control call-to-action__form-control", placeholder = Html.DisplayNameFor(d => feedback.Phone) })
                        @Html.ValidationMessageFor(m => feedback.Phone)
                        @*<input type="text" class="form-control call-to-action__form-control" placeholder="Телефон">*@
                    </div>
                    <div class="form-group call-to-action__form-group">
                        <input class="" id="Confirm_terms" name="Confirm_terms" placeholder="Имя" type="checkbox">
                        <span class="personal-data-comment">Отправляя данную форму, я даю <a href="~/Content/Policy/pd_agreement_pyramid.pdf" target="_blank">согласие</a> на обработку моих персональных данных в соответствии с <a href="~/Content/Policy/pd_politics_pyramid.pdf" target="_blank">политикой обработки ПД</a>.</span>

                    </div>
                    <div class="form-group">
                        <div class="error-scope" style="color:red;"></div>
                    </div>
                    <button class="call-to-action__btn">Отправить запрос</button>
                </form>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            </div>
        </div>
    </div>
</div>

Pyramid/Views/Event/PartialSliderBanner.cshtml
<div class="page__slider-container">
    <ul class="page__slider">
        <li class="page__slide">
            <img src="~/Content/img/testslide.png" alt="" />
        </li>
        <li class="page__slide">
            <img src="~/Content/img/testslide.png" alt="" />
        </li>
        <li class="page__slide">
            <img src="~/Content/img/testslide.png" alt="" />
        </li>
        <li class="page__slide">
            <img src="~/Content/img/testslide.png" alt="" />
        </li>
    </ul>
</div>
<script>
            $('.page__slider').bxSlider({
                slideMargin: 5,
                controls: false,
                prevText: '',
                nextText: '',
                pager: true

            });

</script>

Pyramid/Views/Event/TemplateCategoryFromEventProduct.cshtml
@model int

<div class="event__product">
    <p>Категория</p>
    @Html.DropDownList("catFor", new SelectList(ViewBag.CategoriesSelectListItem, "Value", "Text"), "Выбрать", new { @class = "form-control js-category-from-event-product", data_ajaxindex = Model })

    <div class="js-product-select">

    </div>
</div>

Pyramid/Views/Event/TemplateEventProductFromCategoryId.cshtml
@model int
<label>Товар</label>
@Html.DropDownList(string.Format("Products[{0}].Id", Model), new SelectList(ViewBag.ProductsSelectListItem, "Value", "Text"), "Выбрать", new { @class = "form-control js-event-product" })